### ISSUE TITLE
zynq7010 cnn

### ISSUE THREAD

**Issue by claudeye** [wysjixiang/ZYNQ7010_CNN_Implementation#1]
请问这个要怎么复现，可以进行图像的处理吗

**Comment by wysjixiang** [comment]
Hi，

这个项目代码只包含CNN前向传播的卷积核心模块，因此如果要实现完整的图像处理，首先你需要添加自己板子的输入输出接口，其次你需要训练好对应的节点参数，然后根据自己的实际需求(根据卷积窗口大小等)修改部分框架代码。

项目的框架可以参考更新的README.md文档以及项目代码。
