### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by zhouweic36** [wysjixiang/ZYNQ7010_CNN_Implementation#2]
这个实现的功能是 提取了32*32图像的CNN特征吧，如果要实现像yolov3tiny类似算法的目标检测，是不是还需要改很多？

**Comment by wysjixiang** [comment]
结构需要做一定修改，并且一些计算单元需要重构，比如卷积模块（本工程的卷积是2X2尺寸）；另外你还需要添加额外的模块比如concact。但是大部分的计算模块你可以用本工程的做参考，FP16精度数据的运算都已经实现，剩下的工作内容我想主要还是按照你自己的训练网络搭建模块即可。
